apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservicep
spec:
  selector:
    matchLabels:
      app: adservicep
  template:
    metadata:
      labels:
        app: adservicep
    spec:
      containers:
        - name: adservicep
          image: random-online-catalog-adservicep:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8081
          # readinessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     path: "/_healthz"
          #     port: 8080
          #     httpHeaders:
          #     - name: "Cookie"
          #       value: "shop_session-id=x-readiness-probe"
          # livenessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     path: "/_healthz"
          #     port: 8080
          #     httpHeaders:
          #     - name: "Cookie"
          #       value: "shop_session-id=x-liveness-probe"
          env:
            - name: WAITING_TIME_MIN
              value: "25"
            - name: WAITING_TIME_MAX
              value: "250"
            - name: WAITING_TIME_TIMEOUT
              value: "100"
          # resources:
          #   requests:
          #     cpu: 350m
          #     memory: 80Mi
          #   limits:
          #     cpu: 450m
          #     memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: adservicep
spec:
  type: ClusterIP
  selector:
    app: adservicep
  ports:
    - port: 8081
