apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogservice
spec:
  selector:
    matchLabels:
      app: catalogservice
  template:
    metadata:
      labels:
        app: catalogservice
    spec:
      containers:
        - name: catalogservice
          image: random-online-catalog-catalogservice:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8088          
---
apiVersion: v1
kind: Service
metadata:
  name: catalogservice
spec:
  type: ClusterIP
  selector:
    app: catalogservice
  ports:
    - port: 8088
