apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: default
      containers:
        - name: frontend
          image: random-online-catalog-frontend:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          # readinessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     path: "/_healthz"
          #     port: 8080
          #     httpHeaders:
          #     - name: "Cookie"
          #       value: "shop_session-id=x-readiness-probe"
          # livenessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     path: "/_healthz"
          #     port: 8080
          #     httpHeaders:
          #     - name: "Cookie"
          #       value: "shop_session-id=x-liveness-probe"
          env:
          - name: PERSONALIZED_ADSERVICE_ADDR
            value: "http://adservicep.default.svc.cluster.local:8081"
          - name: LEGACY_ADSERVICE_ADDR
            value: "http://adservicep.default.svc.cluster.local:8082"            
          - name: CATALOG_SERVICE_ADDR
            value: "http://catalogservice.default.svc.cluster.local:8088"
          # resources:
          #   requests:
          #     cpu: 350m
          #     memory: 80Mi
          #   limits:
          #     cpu: 450m
          #     memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
